### ISSUE TITLE
fix: Make images transparent

### ISSUE THREAD

**Issue by oSumAtrIX** [validcube/validcube#1]
# Issue

Currently, your profile readme looks like this in dark mode:

![image](https://github.com/validcube/validcube/assets/13122796/1f59052a-e04e-4015-aba3-6aca84648ebd)

# Solution

Make the images transparent.

**Comment by validcube** [comment]
👋 Hello!

Your issue has been triaged in Trello, we may informed you if further information is needed!

💖 Thank you for your contribution!

**Comment by validcube** [comment]
🥞 Hello!

Your issue has been fixed in #2, feel free to reopen!

💖 Thank you for your contribution!
